version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

  pinot-controller:
    image: apachepinot/pinot:latest
    command: StartController -zkAddress zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - "9000:9000" # Web UI
    environment:
      JAVA_OPTS: "-Xms512M -Xmx512M"

  pinot-broker:
    image: apachepinot/pinot:latest
    command: StartBroker -zkAddress zookeeper:2181
    depends_on:
      - pinot-controller
    ports:
      - "8099:8099"

  pinot-server:
    image: apachepinot/pinot:latest
    command: StartServer -zkAddress zookeeper:2181
    depends_on:
      - pinot-controller

  pinot-minion:
    image: apachepinot/pinot:latest
    command: StartMinion -zkAddress zookeeper:2181
    depends_on:
      - pinot-controller

  producer:
    image: python:3.12
    depends_on:
      - pinot-controller
    command: bash -c "pip install -r requirements.txt && python produce_random_events.py"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - default

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "superset-secret"
    volumes:
      - ./superset:/app/superset_home
    depends_on:
      - pinot-controller
    command: >
      /bin/sh -c " superset db upgrade && superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin && superset init && superset run -h 0.0.0.0 -p 8088"

  pinot-init:
    image: python:3.12
    depends_on:
      - pinot-controller
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install requests && python init_pinot.py"
    networks:
      - default

  superset-init:
    image: python:3.12
    depends_on:
      - superset
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install requests && python init_superset.py"
    networks:
      - default
